### ISSUE TITLE
PopToRoot in NavigationController

### ISSUE THREAD

**Issue by Ikloo** [SpectralDragon/LightRoute#10]
Привет!
Я делал пул реквест с обновленным закрытием модулей по аналогии с тем, что есть уже(через TransitionPromise), но в обновлении я этого не нашел. В связи с этим у меня возникла такая проблема:
**Как мне сделать переход к рутовому VC в navigationController's стеке без передачи controllerId?**

И почему ты все таки решил оставить старую реализацию закрытия модуля(без TransitionPromise, без конфигурирования animated как в других методах, без выбора типа закрытия)?

**Comment by SpectralDragon** [comment]
Это было моим упущением. Переделаем..

**Comment by SpectralDragon** [comment]
Все! Теперь есть `CloseTransitionNode`. Почти тоже самое, что и ты делал, но немного переоформил.

**Comment by Ikloo** [comment]
@SpectralDragon не нужно извиняться!
Супер!
