### ISSUE TITLE
ну и чо ты мне сломал

### ISSUE THREAD

**Issue by Starmel** [SpectralDragon/LightRoute#30]
Прекол

**2.1.19**
![image](https://user-images.githubusercontent.com/8287942/46482364-23244400-c7fe-11e8-8183-e25c96f30f2b.png)

**Comment by SpectralDragon** [comment]
Just use "LightRoute ~> 2.19.0"

**Comment by Starmel** [comment]
допомогло
`pod 'LightRoute',: git => 'https://github.com/SpectralDragon/LightRoute.git',: tag => '2.1.19'`

Думаю потрібно оновити опис проекту, що нові версії не сумісні з попередніми версіями Свіфт (до 4.2)
