### ISSUE TITLE
Update cocoapod to version 1.0.8

### ISSUE THREAD

**Issue by ambas** [SpectralDragon/LightRoute#6]
Hi. I'm so impressed with your work its make my router part pretty neat.  
I saw you already merged PR about close module and bump that part to version 1.0.8.

Do you have any plan to move cocoapod to version 1.0.8 also? because now its still 1.0.6 so for now I have to point to master branch in podfile manually.

Thanks!

**Comment by SpectralDragon** [comment]
@ambas I update pod version)
Nica a have day!
