### ISSUE TITLE
Standart DI (via Configurator)

### ISSUE THREAD

**Issue by Ikloo** [SpectralDragon/LightRoute#9]
Привет! 
У нас в проекте возникла проблема стандартного DI с помощью иницализатора и конфигуртора в рантайме приложения(необходимо было в модуле подменить интерактор при создании модуля). С этим отчасти справилась Storyboard factory(инициализацией нового контроллера в Router'е), но необходимо было дальше передать этот контроллер в LightRoute с настройками навигации/анимации/инпута.

Было придумано такое решение: 
```
let storyboard = UIStoryboard(name: storyboardName, bundle: Bundle.main)
let factory = StoryboardFactory(storyboard: storyboard, restorationId: viewControllerId)

guard let controller = factory.instantiateTransitionHandler as? ViewController else { return }
		
_ = ViewControllerModuleInitializer(viewController: controller, forLogin: true)
		
transitionHandler
	.toViewController(controller, to: ViewControllerModuleInput.self)
	.to(preferred: .navigationController(preferredStyle: .push))
	.then { moduleInput in
		moduleInput.configure(with: "configure module input")
        }
```

т.е. был добавлен метод `toViewController<T>(_ destination: UIViewController, to type: T.Type) -> TransitionPromise<T>` в source файлы пода. 

Реализация метода выглядит так: 
```
func toViewController<T>(_ destination: UIViewController, to type: T.Type) -> TransitionPromise<T> {
		let promise = TransitionPromise(root: self, destination: destination, for: type)
		
		// Default transition action.
		promise.postLintAction {
			self.present(destination, animated: true, completion: nil)
		}
		
		return promise
	}
```

На данный момент такой метод работает вполне отлично. Хотелось бы увидеть его в твоем поде. Если такое решение устраивает, то могу сделать пул реквест с изменениями. :)

**Comment by SpectralDragon** [comment]
Привет! Спасибо за отзыв :)
Вариант с передачей уже сконфигурированого контроллера мне не нравится. Быть может сделать метод `apply(to:)` который будет возвращать destination controller?
В конце концов реализация будет такой:

````swift

let storyboard = UIStoryboard(name: storyboardName, bundle: Bundle.main)
let factory = StoryboardFactory(storyboard: storyboard, restorationId: viewControllerId)

transitionHandler
	.forStoryboard(factory: factory, to type: ViewControllerModuleInput.self)
	.apply(to: { controller in 
		_ = ViewControllerModuleInitializer(viewController: controller, forLogin: true)
	})
	.to(preferred: .navigationController(preferredStyle: .push))
	.then { moduleInput in
		moduleInput.configure(with: "configure module input")
        }
````

Ну или так:

````swift

func viewControllerConfigurator(controller: ViewController) {
	// Your configurations
}

let storyboard = UIStoryboard(name: storyboardName, bundle: Bundle.main)
let factory = StoryboardFactory(storyboard: storyboard, restorationId: viewControllerId)

transitionHandler
	.forStoryboard(factory: factory, to type: ViewControllerModuleInput.self)
	.apply(to: self.viewControllerConfigurator)
	.to(preferred: .navigationController(preferredStyle: .push))
	.then { moduleInput in
		moduleInput.configure(with: "configure module input")
        }
````

Как считаешь? 🤔

А вообще, для этих целей обычно использую CustomTransition)

**Comment by Ikloo** [comment]
Мы сначала тоже думали использовать CustomTransition, но решили, что это нарушение логики в переходе конфигурировать модуль, это надо делать до перехода. 
Первый метод как-то посимпатичнее выглядит, ты просто отдаешь наружу контроллер, а там уже каждый сам с ним разбирается как хочет. 
Тогда по итогу можно отвязаться от фабрики и забирать(конфигурировать контроллер) при любом виде перехода в LightRoute. 
Отличное решение!👍🏼

**Comment by SpectralDragon** [comment]
Готово! Метод `apply(to:)` добавил :)
